[project]
name = "url-to-markdown"
version = "0.1.0"
description = "CLI tool to fetch URLs and convert to markdown"
dependencies = [
    "firecrawl",
    "click",
    "python-dotenv",
    "anthropic",
    "pytest",
    "prompt-toolkit>=3.0.50",
    "rich>=13.9.4",
    "pyperclip>=1.9.0",
    "tavily-python>=0.5.1",
    "pillow>=11.1.0",
    "groq>=0.18.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
url-to-md = "main:cli"

[tool.hatch.build.targets.wheel]
packages = ["modules"]

[tool.hatch.build]
include = [
    "main.py",
    "modules/**/*.py",
]
